"""
Notifications Infra — Schema Spec v1.3, Section 2.6.

Table: push_subscriptions. This was the 32nd and final table when the
model layer was first completed to match the FINAL PROMPT Step 2 schema.

resident_notifications (below) was added later, in-app Phase 1
(user-requested): a targeted, per-Resident notification feed — e.g.
"your maintenance is overdue" — distinct from PushSubscription (delivery
plumbing, no content) and from Notice (operations.py — broadcast,
society-wide, no audience targeting). No real-time delivery here either
— a Resident sees it via the bell icon next time they open the app;
generation is a standalone cron script (scripts/
generate_overdue_notifications.py), same reasoning as
upload_service's orphan-proof cleanup: no in-app scheduler to hang a
periodic job off of.
"""
import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, ForeignKey, Index, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.core.db import Base
from app.models.enums import NotificationType, SubscriptionPlatform
from app.models.mixins import UUIDPKMixin
from app.models.pg_enum import pg_enum


class PushSubscription(Base, UUIDPKMixin):
    """Minimal delivery infra for Web Push / FCM (Section 1, audit gap #4).
    NOT a generic notification-feed table — no content, read-status, or
    audience-targeting logic here (that stays out of MVP scope)."""

    __tablename__ = "push_subscriptions"

    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=False
    )
    # FCM token string, or serialized Web Push subscription (endpoint+keys) —
    # generic on purpose (v1.1 fix, not FCM-only)
    subscription_data: Mapped[str] = mapped_column(Text, nullable=False)
    platform: Mapped[SubscriptionPlatform] = mapped_column(
        pg_enum(SubscriptionPlatform, "subscription_platform_enum"), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )
    revoked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    __table_args__ = (
        # avoid duplicate active subscriptions per device
        Index(
            "ux_push_subscriptions_active",
            "user_id",
            "subscription_data",
            unique=True,
            postgresql_where="revoked_at IS NULL",
        ),
    )


class ResidentNotification(Base, UUIDPKMixin):
    """A targeted, per-Resident notification — Phase 1 only knows
    MAINTENANCE_OVERDUE, generated by generate_overdue_notifications()
    for every active Owner/Tenant on the overdue property (a property can
    have more than one active resident, Section 12). related_due_id is
    the dedup key alongside resident_id/type — the unique index below
    stops the cron script re-notifying the same person about the same
    due on every run."""

    __tablename__ = "resident_notifications"

    society_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("societies.id"), nullable=False
    )
    resident_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id"), nullable=False
    )
    type: Mapped[NotificationType] = mapped_column(
        pg_enum(NotificationType, "notification_type_enum"), nullable=False
    )
    title: Mapped[str] = mapped_column(String(200), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    related_due_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("maintenance_dues.id"), nullable=True
    )
    is_read: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False
    )

    __table_args__ = (
        UniqueConstraint(
            "resident_id", "related_due_id", "type",
            name="ux_resident_notifications_dedup",
        ),
    )
