import { apiClient } from "@/api/client";

/** Phase 1 in-app notifications (user-requested) — a targeted, per-
 * Resident feed, distinct from the broadcast-only /notices. Only
 * MAINTENANCE_OVERDUE exists today, generated by a daily cron script
 * (scripts/generate_overdue_notifications.py), not in real time. */
export interface ResidentNotificationOut {
  id: string;
  type: "MAINTENANCE_OVERDUE";
  title: string;
  message: string;
  related_due_id: string | null;
  is_read: boolean;
  created_at: string;
}

export interface Page<T> {
  items: T[];
  total: number;
  skip: number;
  limit: number;
}

export const notificationsApi = {
  mine: (skip = 0, limit = 20) => apiClient.get<Page<ResidentNotificationOut>>("/notifications/mine", { params: { skip, limit } }),
  unreadCount: () => apiClient.get<{ count: number }>("/notifications/unread-count"),
  markRead: (id: string) => apiClient.patch<ResidentNotificationOut>(`/notifications/${id}/read`),
  markAllRead: () => apiClient.post<{ count: number }>("/notifications/mark-all-read"),
};
