"""initial schema — all 32 tables (Schema Spec v1.3)

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-12

Hand-written (not autogenerated — no live DB available at authoring time).
Creates every enum type explicitly, then every table in FK-dependency-safe
order, with every constraint traced to the FINAL PROMPT Step 2 spec.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# ---------------------------------------------------------------------------
# Enum definitions: (pg_type_name, [values])
# ---------------------------------------------------------------------------
ENUMS: list[tuple[str, list[str]]] = [
    ("society_status_enum", ["PENDING", "ACTIVE", "SUSPENDED"]),
    ("user_status_enum", ["PENDING", "ACTIVE", "REJECTED", "INACTIVE"]),
    ("role_enum", ["PLATFORM_OWNER", "ADMIN", "SUB_ADMIN", "MANAGER", "RESIDENT", "SECURITY_GUARD"]),
    ("location_type_enum", ["WING", "ROW"]),
    ("house_type_enum", ["FLAT", "BUNGALOW"]),
    ("relationship_type_enum", ["OWNER", "TENANT"]),
    ("role_request_type_enum", ["SUB_ADMIN_RESIGNATION"]),
    ("role_request_status_enum", ["PENDING", "APPROVED", "REJECTED"]),
    ("maintenance_due_status_enum", ["PENDING", "PAID"]),
    ("payment_method_enum", ["MOCK_ONLINE", "MANUAL_UPI", "MANUAL_CASH"]),
    ("payment_status_enum", ["PENDING_APPROVAL", "PAID", "REJECTED"]),
    ("proof_type_enum", ["UPI_SCREENSHOT", "CASH_RECEIPT"]),
    ("payment_audit_action_enum", ["CREATED", "PAID_MARKED", "APPROVED", "REJECTED", "CORRECTED"]),
    ("wallet_txn_type_enum", ["MAINTENANCE_CREDIT", "ADJUSTMENT"]),
    ("entry_type_enum", ["INCOME", "EXPENSE"]),
    ("entry_source_enum", ["MANUAL", "MAINTENANCE_PAYMENT", "EXPENSE_BILL", "ADJUSTMENT"]),
    ("todo_status_enum", ["PENDING", "IN_PROGRESS", "DONE"]),
    ("complaint_status_enum", ["OPEN", "IN_PROGRESS", "RESOLVED", "CLOSED"]),
    ("visitor_status_enum", ["PRE_APPROVED", "EXPECTED", "ENTERED", "EXITED", "CANCELLED"]),
    ("booking_status_enum", ["PENDING", "APPROVED", "REJECTED", "CANCELLED"]),
    ("proposal_scope_enum", ["SOCIETY", "WING", "ROW"]),
    ("proposal_status_enum", ["OPEN", "APPROVED", "WITHDRAWN"]),
    ("voter_role_enum", ["RESIDENT", "SUB_ADMIN"]),
    ("vote_enum", ["APPROVE", "REJECT"]),
    ("expense_bill_status_enum", ["DRAFT", "PENDING_APPROVAL", "APPROVED", "REJECTED"]),
    ("decision_enum", ["APPROVE", "REJECT"]),
    ("subscription_platform_enum", ["WEB", "ANDROID", "IOS"]),
]


def _enum(name: str) -> postgresql.ENUM:
    """Reference an already-created enum type without re-issuing CREATE TYPE."""
    return postgresql.ENUM(name=name, create_type=False)


def upgrade() -> None:
    # --- 1. Enum types --------------------------------------------------
    for name, values in ENUMS:
        postgresql.ENUM(*values, name=name).create(op.get_bind(), checkfirst=True)

    uuid_pk = lambda: sa.Column(
        "id", postgresql.UUID(as_uuid=True), primary_key=True,
        server_default=sa.text("gen_random_uuid()"),
    )
    ts_cols = lambda: [
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    ]
    created_only = lambda: [
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    ]

    # --- 2. societies -----------------------------------------------------
    op.create_table(
        "societies",
        uuid_pk(),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("code", sa.String(50), nullable=False, unique=True),
        sa.Column("status", _enum("society_status_enum"), nullable=False, server_default="PENDING"),
        sa.Column("address", sa.Text, nullable=True),
        sa.Column("city", sa.String(100), nullable=True),
        sa.Column("state", sa.String(100), nullable=True),
        sa.Column("pincode", sa.String(10), nullable=True),
        *ts_cols(),
    )

    # --- 3. users -----------------------------------------------------
    op.create_table(
        "users",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=True),
        sa.Column("full_name", sa.String(150), nullable=False),
        sa.Column("mobile", sa.String(15), nullable=False),
        sa.Column("email", sa.String(255), nullable=True),
        sa.Column("status", _enum("user_status_enum"), nullable=False, server_default="PENDING"),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("approved_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        *ts_cols(),
        sa.UniqueConstraint("society_id", "id", name="ux_users_society_id_id"),
    )
    op.create_index(
        "ux_users_society_mobile", "users", ["society_id", "mobile"],
        unique=True, postgresql_where=sa.text("society_id IS NOT NULL"),
    )
    op.create_index(
        "ux_users_platform_owner_mobile", "users", ["mobile"],
        unique=True, postgresql_where=sa.text("society_id IS NULL"),
    )

    # --- 4. user_roles -----------------------------------------------------
    op.create_table(
        "user_roles",
        uuid_pk(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("role", _enum("role_enum"), nullable=False),
        sa.Column("assigned_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ux_user_roles_active", "user_roles", ["user_id", "role"],
        unique=True, postgresql_where=sa.text("revoked_at IS NULL"),
    )

    # --- 5. society_locations -----------------------------------------------------
    op.create_table(
        "society_locations",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("name", sa.String(100), nullable=False),
        sa.Column("location_type", _enum("location_type_enum"), nullable=False),
        *ts_cols(),
        sa.UniqueConstraint("society_id", "location_type", "name", name="ux_location_society_type_name"),
        sa.UniqueConstraint("society_id", "id", name="ux_society_locations_society_id_id"),
    )

    # --- 6. properties -----------------------------------------------------
    op.create_table(
        "properties",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("location_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("house_number", sa.String(50), nullable=False),
        sa.Column("house_type", _enum("house_type_enum"), nullable=False),
        sa.Column("floor_number", sa.Integer, nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="ACTIVE"),
        *ts_cols(),
        sa.CheckConstraint("house_type != 'FLAT' OR floor_number IS NOT NULL", name="ck_properties_flat_requires_floor"),
        sa.UniqueConstraint("society_id", "house_number", name="ux_properties_society_house"),
        sa.UniqueConstraint("society_id", "id", name="ux_properties_society_id_id"),
        sa.ForeignKeyConstraint(
            ["society_id", "location_id"], ["society_locations.society_id", "society_locations.id"],
            name="fk_properties_society_location",
        ),
    )

    # --- 7. property_residents -----------------------------------------------------
    op.create_table(
        "property_residents",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("property_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("resident_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("relationship_type", _enum("relationship_type_enum"), nullable=False),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        sa.Column("start_date", sa.Date, nullable=True),
        sa.Column("end_date", sa.Date, nullable=True),
        *created_only(),
        sa.ForeignKeyConstraint(
            ["society_id", "property_id"], ["properties.society_id", "properties.id"],
            name="fk_property_residents_society_property",
        ),
        sa.ForeignKeyConstraint(
            ["society_id", "resident_id"], ["users.society_id", "users.id"],
            name="fk_property_residents_society_resident",
        ),
    )
    op.create_index(
        "ux_property_residents_active", "property_residents",
        ["property_id", "resident_id", "relationship_type"],
        unique=True, postgresql_where=sa.text("is_active = true"),
    )

    # --- 8. sub_admin_scopes -----------------------------------------------------
    op.create_table(
        "sub_admin_scopes",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("sub_admin_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("location_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("assigned_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["society_id", "sub_admin_id"], ["users.society_id", "users.id"],
            name="fk_sub_admin_scopes_society_subadmin",
        ),
        sa.ForeignKeyConstraint(
            ["society_id", "location_id"], ["society_locations.society_id", "society_locations.id"],
            name="fk_sub_admin_scopes_society_location",
        ),
    )
    op.create_index(
        "ux_sub_admin_scopes_active", "sub_admin_scopes", ["sub_admin_id", "location_id"],
        unique=True, postgresql_where=sa.text("revoked_at IS NULL"),
    )

    # --- 9. role_requests -----------------------------------------------------
    op.create_table(
        "role_requests",
        uuid_pk(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("request_type", _enum("role_request_type_enum"), nullable=False, server_default="SUB_ADMIN_RESIGNATION"),
        sa.Column("status", _enum("role_request_status_enum"), nullable=False, server_default="PENDING"),
        sa.Column("reason", sa.Text, nullable=True),
        sa.Column("reviewed_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_reason", sa.Text, nullable=True),
        *created_only(),
        sa.ForeignKeyConstraint(
            ["society_id", "user_id"], ["users.society_id", "users.id"],
            name="fk_role_requests_society_user",
        ),
    )

    # --- 10. task_suggestions (platform-global) -----------------------------------------------------
    op.create_table(
        "task_suggestions",
        uuid_pk(),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        *created_only(),
    )

    # --- 11. expense_bills (created before account_entries needs it) -----------------------------------------------------
    op.create_table(
        "expense_bills",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("amount", sa.Numeric(12, 2), nullable=False),
        sa.Column("category", sa.String(100), nullable=True),
        sa.Column("status", _enum("expense_bill_status_enum"), nullable=False, server_default="DRAFT"),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("finalized_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True),
        *ts_cols(),
        sa.CheckConstraint("amount > 0", name="ck_expense_bills_amount_positive"),
        sa.CheckConstraint("status != 'DRAFT' OR finalized_by IS NULL", name="ck_expense_bills_draft_no_finalizer"),
        sa.UniqueConstraint("society_id", "id", name="ux_expense_bills_society_id_id"),
    )

    # --- 12. maintenance_dues -----------------------------------------------------
    op.create_table(
        "maintenance_dues",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("property_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("amount", sa.Numeric(12, 2), nullable=False),
        sa.Column("due_date", sa.Date, nullable=False),
        sa.Column("status", _enum("maintenance_due_status_enum"), nullable=False, server_default="PENDING"),
        sa.Column("billing_month", sa.Date, nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("amount >= 0", name="ck_maintenance_dues_amount_nonneg"),
        sa.UniqueConstraint("society_id", "property_id", "billing_month", name="ux_maintenance_due_month"),
        sa.UniqueConstraint("society_id", "id", name="ux_maintenance_dues_society_id_id"),
        sa.ForeignKeyConstraint(
            ["society_id", "property_id"], ["properties.society_id", "properties.id"],
            name="fk_maintenance_dues_society_property",
        ),
    )

    # --- 13. payments -----------------------------------------------------
    op.create_table(
        "payments",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("maintenance_due_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("property_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("resident_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("payment_method", _enum("payment_method_enum"), nullable=False),
        sa.Column("amount", sa.Numeric(12, 2), nullable=False),
        sa.Column("status", _enum("payment_status_enum"), nullable=False, server_default="PENDING_APPROVAL"),
        sa.Column("reference_number", sa.String(150), nullable=True),
        sa.Column("idempotency_key", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("paid_marked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("rejection_reason", sa.Text, nullable=True),
        *ts_cols(),
        sa.CheckConstraint("amount > 0", name="ck_payments_amount_positive"),
        sa.UniqueConstraint("maintenance_due_id", "idempotency_key", name="ux_payments_due_idempotency"),
        sa.ForeignKeyConstraint(
            ["society_id", "property_id"], ["properties.society_id", "properties.id"],
            name="fk_payments_society_property",
        ),
        sa.ForeignKeyConstraint(
            ["society_id", "resident_id"], ["users.society_id", "users.id"],
            name="fk_payments_society_resident",
        ),
        sa.ForeignKeyConstraint(
            ["society_id", "maintenance_due_id"], ["maintenance_dues.society_id", "maintenance_dues.id"],
            name="fk_payments_society_due",
        ),
    )
    op.create_index(
        "ux_payments_one_pending_per_due", "payments", ["maintenance_due_id"],
        unique=True, postgresql_where=sa.text("status = 'PENDING_APPROVAL'"),
    )

    # --- 14. account_entries -----------------------------------------------------
    op.create_table(
        "account_entries",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("entry_type", _enum("entry_type_enum"), nullable=False),
        sa.Column("source", _enum("entry_source_enum"), nullable=False),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("amount", sa.Numeric(12, 2), nullable=False),
        sa.Column("entry_date", sa.Date, nullable=False),
        sa.Column("is_edited", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("last_edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("related_payment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("payments.id"), nullable=True),
        sa.Column("related_expense_bill_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("expense_bills.id"), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        *ts_cols(),
        sa.CheckConstraint(
            "(source IN ('MANUAL','MAINTENANCE_PAYMENT','EXPENSE_BILL') AND amount > 0) OR source = 'ADJUSTMENT'",
            name="ck_account_entries_amount_sign",
        ),
        sa.CheckConstraint("source != 'ADJUSTMENT' OR entry_type = 'INCOME'", name="ck_account_entries_adjustment_is_income"),
        sa.CheckConstraint(
            "source != 'MAINTENANCE_PAYMENT' OR (entry_type = 'INCOME' AND related_payment_id IS NOT NULL AND related_expense_bill_id IS NULL)",
            name="ck_account_entries_maintenance_payment_shape",
        ),
        sa.CheckConstraint(
            "source != 'EXPENSE_BILL' OR (entry_type = 'EXPENSE' AND related_expense_bill_id IS NOT NULL AND related_payment_id IS NULL)",
            name="ck_account_entries_expense_bill_shape",
        ),
        sa.CheckConstraint(
            "source != 'MANUAL' OR (related_payment_id IS NULL AND related_expense_bill_id IS NULL)",
            name="ck_account_entries_manual_shape",
        ),
    )
    op.create_index(
        "ux_account_entries_payment_once", "account_entries", ["related_payment_id"],
        unique=True, postgresql_where=sa.text("source = 'MAINTENANCE_PAYMENT'"),
    )
    op.create_index(
        "ux_account_entries_expense_bill_once", "account_entries", ["related_expense_bill_id"],
        unique=True, postgresql_where=sa.text("source = 'EXPENSE_BILL'"),
    )

    # --- 15. payment_proofs -----------------------------------------------------
    op.create_table(
        "payment_proofs",
        uuid_pk(),
        sa.Column("payment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("payments.id"), nullable=False),
        sa.Column("proof_type", _enum("proof_type_enum"), nullable=False),
        sa.Column("file_url", sa.Text, nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("uploaded_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
    )

    # --- 16. payment_audit_logs (immutable) -----------------------------------------------------
    op.create_table(
        "payment_audit_logs",
        uuid_pk(),
        sa.Column("payment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("payments.id"), nullable=False),
        sa.Column("action", _enum("payment_audit_action_enum"), nullable=False),
        sa.Column("old_status", sa.String(50), nullable=True),
        sa.Column("new_status", sa.String(50), nullable=True),
        sa.Column("old_amount", sa.Numeric(12, 2), nullable=True),
        sa.Column("new_amount", sa.Numeric(12, 2), nullable=True),
        sa.Column("reason", sa.Text, nullable=True),
        sa.Column("performed_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        *created_only(),
    )

    # --- 17. wallets -----------------------------------------------------
    op.create_table(
        "wallets",
        uuid_pk(),
        sa.Column("resident_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False, unique=True),
        sa.Column("balance", sa.Numeric(14, 2), nullable=False, server_default="0"),
        *ts_cols(),
        sa.CheckConstraint("balance >= 0", name="ck_wallets_balance_nonneg"),
    )

    # --- 18. wallet_transactions -----------------------------------------------------
    op.create_table(
        "wallet_transactions",
        uuid_pk(),
        sa.Column("wallet_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("wallets.id"), nullable=False),
        sa.Column("transaction_type", _enum("wallet_txn_type_enum"), nullable=False),
        sa.Column("amount", sa.Numeric(14, 2), nullable=False),
        sa.Column("payment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("payments.id"), nullable=True),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        *created_only(),
    )
    op.create_index(
        "ux_wallet_txn_maintenance_credit_once", "wallet_transactions",
        ["wallet_id", "payment_id", "transaction_type"],
        unique=True, postgresql_where=sa.text("transaction_type = 'MAINTENANCE_CREDIT'"),
    )

    # --- 19. payment_corrections -----------------------------------------------------
    op.create_table(
        "payment_corrections",
        uuid_pk(),
        sa.Column("payment_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("payments.id"), nullable=False),
        sa.Column("old_amount", sa.Numeric(12, 2), nullable=False),
        sa.Column("new_amount", sa.Numeric(12, 2), nullable=False),
        sa.Column("difference", sa.Numeric(12, 2), nullable=False),
        sa.Column("reason", sa.Text, nullable=False),
        sa.Column("corrected_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("corrected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("wallet_adjustment_txn_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("wallet_transactions.id"), nullable=True),
        sa.Column("ledger_adjustment_entry_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("account_entries.id"), nullable=True),
        sa.CheckConstraint("difference = new_amount - old_amount", name="ck_payment_corrections_diff"),
    )
    op.create_index(
        "ux_payment_corrections_wallet_txn", "payment_corrections", ["wallet_adjustment_txn_id"],
        unique=True, postgresql_where=sa.text("wallet_adjustment_txn_id IS NOT NULL"),
    )
    op.create_index(
        "ux_payment_corrections_ledger_entry", "payment_corrections", ["ledger_adjustment_entry_id"],
        unique=True, postgresql_where=sa.text("ledger_adjustment_entry_id IS NOT NULL"),
    )

    # --- 20. account_entry_edit_history -----------------------------------------------------
    op.create_table(
        "account_entry_edit_history",
        uuid_pk(),
        sa.Column("account_entry_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("account_entries.id"), nullable=False),
        sa.Column("previous_title", sa.String(200), nullable=True),
        sa.Column("previous_description", sa.Text, nullable=True),
        sa.Column("previous_amount", sa.Numeric(12, 2), nullable=True),
        sa.Column("previous_entry_date", sa.Date, nullable=True),
        sa.Column("edited_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=False),
    )

    # --- 21. manager_todos -----------------------------------------------------
    op.create_table(
        "manager_todos",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("manager_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("task_suggestion_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("task_suggestions.id"), nullable=False),
        sa.Column("task_date", sa.Date, nullable=False),
        sa.Column("status", _enum("todo_status_enum"), nullable=False, server_default="PENDING"),
        sa.Column("assigned_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        *ts_cols(),
        sa.ForeignKeyConstraint(
            ["society_id", "manager_id"], ["users.society_id", "users.id"],
            name="fk_manager_todos_society_manager",
        ),
    )

    # --- 22. complaints -----------------------------------------------------
    op.create_table(
        "complaints",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("property_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("resident_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("category", sa.String(100), nullable=False),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("description", sa.Text, nullable=False),
        sa.Column("status", _enum("complaint_status_enum"), nullable=False, server_default="OPEN"),
        *ts_cols(),
        sa.ForeignKeyConstraint(
            ["society_id", "property_id"], ["properties.society_id", "properties.id"],
            name="fk_complaints_society_property",
        ),
        sa.ForeignKeyConstraint(
            ["society_id", "resident_id"], ["users.society_id", "users.id"],
            name="fk_complaints_society_resident",
        ),
    )

    # --- 23. complaint_assignments -----------------------------------------------------
    op.create_table(
        "complaint_assignments",
        uuid_pk(),
        sa.Column("complaint_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("complaints.id"), nullable=False),
        sa.Column("assigned_to", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("assigned_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ux_complaint_assignments_current", "complaint_assignments", ["complaint_id"],
        unique=True, postgresql_where=sa.text("completed_at IS NULL"),
    )

    # --- 24. visitors -----------------------------------------------------
    op.create_table(
        "visitors",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("property_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("resident_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("visitor_name", sa.String(150), nullable=False),
        sa.Column("visitor_mobile", sa.String(15), nullable=True),
        sa.Column("visit_date", sa.Date, nullable=False),
        sa.Column("status", _enum("visitor_status_enum"), nullable=False, server_default="PRE_APPROVED"),
        sa.Column("purpose", sa.String(255), nullable=True),
        *created_only(),
        sa.ForeignKeyConstraint(
            ["society_id", "property_id"], ["properties.society_id", "properties.id"],
            name="fk_visitors_society_property",
        ),
        sa.ForeignKeyConstraint(
            ["society_id", "resident_id"], ["users.society_id", "users.id"],
            name="fk_visitors_society_resident",
        ),
    )

    # --- 25. visitor_logs -----------------------------------------------------
    op.create_table(
        "visitor_logs",
        uuid_pk(),
        sa.Column("visitor_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("visitors.id"), nullable=False),
        sa.Column("guard_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("entry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exit_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text, nullable=True),
        *created_only(),
    )

    # --- 26. notices -----------------------------------------------------
    op.create_table(
        "notices",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("content", sa.Text, nullable=False),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        *ts_cols(),
    )

    # --- 27. amenities -----------------------------------------------------
    op.create_table(
        "amenities",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("name", sa.String(150), nullable=False),
        sa.Column("description", sa.Text, nullable=True),
        sa.Column("is_active", sa.Boolean, nullable=False, server_default=sa.true()),
        *ts_cols(),
        sa.UniqueConstraint("society_id", "id", name="ux_amenities_society_id_id"),
    )

    # --- 28. amenity_bookings -----------------------------------------------------
    op.create_table(
        "amenity_bookings",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("amenity_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("property_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("resident_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("booking_date", sa.Date, nullable=False),
        sa.Column("start_time", sa.Time, nullable=False),
        sa.Column("end_time", sa.Time, nullable=False),
        sa.Column("status", _enum("booking_status_enum"), nullable=False, server_default="PENDING"),
        sa.Column("approved_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        *ts_cols(),
        sa.CheckConstraint("start_time < end_time", name="ck_amenity_bookings_time_range"),
        sa.ForeignKeyConstraint(
            ["society_id", "amenity_id"], ["amenities.society_id", "amenities.id"],
            name="fk_amenity_bookings_society_amenity",
        ),
        sa.ForeignKeyConstraint(
            ["society_id", "property_id"], ["properties.society_id", "properties.id"],
            name="fk_amenity_bookings_society_property",
        ),
        sa.ForeignKeyConstraint(
            ["society_id", "resident_id"], ["users.society_id", "users.id"],
            name="fk_amenity_bookings_society_resident",
        ),
    )

    # --- 29. proposals -----------------------------------------------------
    op.create_table(
        "proposals",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("scope_type", _enum("proposal_scope_enum"), nullable=False),
        sa.Column("scope_location_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("description", sa.Text, nullable=False),
        sa.Column("status", _enum("proposal_status_enum"), nullable=False, server_default="OPEN"),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_by", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        *ts_cols(),
        sa.CheckConstraint(
            "(scope_type = 'SOCIETY' AND scope_location_id IS NULL) OR (scope_type IN ('WING','ROW') AND scope_location_id IS NOT NULL)",
            name="ck_proposals_scope_location_shape",
        ),
        sa.ForeignKeyConstraint(
            ["society_id", "scope_location_id"], ["society_locations.society_id", "society_locations.id"],
            name="fk_proposals_society_scope_location",
        ),
    )

    # --- 30. proposal_votes -----------------------------------------------------
    op.create_table(
        "proposal_votes",
        uuid_pk(),
        sa.Column("proposal_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("proposals.id"), nullable=False),
        sa.Column("voter_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("voter_role", _enum("voter_role_enum"), nullable=False),
        sa.Column("vote", _enum("vote_enum"), nullable=False),
        sa.Column("voted_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("proposal_id", "voter_id", name="ux_proposal_votes_one_per_voter"),
    )

    # --- 31. proposal_vote_history -----------------------------------------------------
    op.create_table(
        "proposal_vote_history",
        uuid_pk(),
        sa.Column("proposal_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("proposals.id"), nullable=False),
        sa.Column("voter_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("old_vote", _enum("vote_enum"), nullable=True),
        sa.Column("new_vote", _enum("vote_enum"), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
    )

    # --- 32. expense_bill_approvals -----------------------------------------------------
    op.create_table(
        "expense_bill_approvals",
        uuid_pk(),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("expense_bill_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("sub_admin_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("decision", _enum("decision_enum"), nullable=False),
        sa.Column("reason", sa.Text, nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("expense_bill_id", "sub_admin_id", name="ux_expense_bill_approvals_once"),
        sa.ForeignKeyConstraint(
            ["society_id", "expense_bill_id"], ["expense_bills.society_id", "expense_bills.id"],
            name="fk_expense_bill_approvals_society_bill",
        ),
        sa.ForeignKeyConstraint(
            ["society_id", "sub_admin_id"], ["users.society_id", "users.id"],
            name="fk_expense_bill_approvals_society_subadmin",
        ),
    )

    # --- 33. push_subscriptions -----------------------------------------------------
    op.create_table(
        "push_subscriptions",
        uuid_pk(),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("subscription_data", sa.Text, nullable=False),
        sa.Column("platform", _enum("subscription_platform_enum"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        "ux_push_subscriptions_active", "push_subscriptions", ["user_id", "subscription_data"],
        unique=True, postgresql_where=sa.text("revoked_at IS NULL"),
    )


def downgrade() -> None:
    # Drop in reverse FK-dependency order
    for table in [
        "push_subscriptions", "expense_bill_approvals", "proposal_vote_history",
        "proposal_votes", "proposals", "amenity_bookings", "amenities", "notices",
        "visitor_logs", "visitors", "complaint_assignments", "complaints",
        "manager_todos", "account_entry_edit_history", "payment_corrections",
        "wallet_transactions", "wallets", "payment_audit_logs", "payment_proofs",
        "account_entries", "payments", "maintenance_dues", "expense_bills",
        "task_suggestions", "role_requests", "sub_admin_scopes",
        "property_residents", "properties", "society_locations", "user_roles",
        "users", "societies",
    ]:
        op.drop_table(table)

    for name, _values in reversed(ENUMS):
        postgresql.ENUM(name=name).drop(op.get_bind(), checkfirst=True)
