"""resident_notifications

Revision ID: 0017_resident_notifications
Revises: 0016_expense_bill_image
Create Date: 2026-09-25

Phase 1 in-app notifications (user-requested): a targeted, per-Resident
feed distinct from the existing broadcast-only Notice table and from
PushSubscription (delivery plumbing, no content/read-state). Only
MAINTENANCE_OVERDUE exists today, generated by a standalone cron script
(scripts/generate_overdue_notifications.py) — no in-app scheduler.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0017_resident_notifications"
down_revision: Union[str, None] = "0016_expense_bill_image"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    notification_type_enum = postgresql.ENUM("MAINTENANCE_OVERDUE", name="notification_type_enum")
    notification_type_enum.create(op.get_bind(), checkfirst=True)
    # create_type=False here — the CREATE TYPE above already made it;
    # without this, op.create_table would try to (re-)create the enum
    # type itself when it visits this column, colliding with the manual
    # create() call (same pattern as migration 0015's account_headings).
    notification_type_column = postgresql.ENUM(
        "MAINTENANCE_OVERDUE", name="notification_type_enum", create_type=False
    )

    op.create_table(
        "resident_notifications",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("society_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("societies.id"), nullable=False),
        sa.Column("resident_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("type", notification_type_column, nullable=False),
        sa.Column("title", sa.String(200), nullable=False),
        sa.Column("message", sa.Text, nullable=False),
        sa.Column("related_due_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("maintenance_dues.id"), nullable=True),
        sa.Column("is_read", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("resident_id", "related_due_id", "type", name="ux_resident_notifications_dedup"),
    )
    op.create_index(
        "ix_resident_notifications_resident_id", "resident_notifications", ["resident_id"]
    )


def downgrade() -> None:
    op.drop_index("ix_resident_notifications_resident_id", table_name="resident_notifications")
    op.drop_table("resident_notifications")
    op.execute("DROP TYPE IF EXISTS notification_type_enum")
